services:
  - docker

language: python
python:
  - 3.5.3
  - 3.6
  - 3.7-dev

install:
  - pip install cython
  - pip install twine
  - pip install -r requirements/ci.txt
  - pip install codecov
  - pip install mypy-lang


script:
  - make cov
  - make doc
  - python setup.py check -rms
  - make mypy


after_success:
  - codecov
  - ./run_docker.sh


deploy:
  provider: pypi
  user: aio-libs-bot
  password:
    secure: "sp/dByzQnX9uncIzU1jFh+JwF/9J1ANFQ0mzLQZbp/fvusRR7XiUqhJxA/3PrTTFgIOW/aLBy8Dy8Oa+e3uM50qvbpJ9wLK+uvlOJ+T+orfBW7iBqYXSl0/nUNbvmS9PPylnOfmN7rbtMVlbNDN4nmKUIPJ+6t+bgrkcADEZ48g8o+1FLz5SYjDk1JZGrvnE7LWTGY3zFtYgWBTxDnNhYVKU97GC1Lt2l7r700Ni/EQI7xxJdzYt//Ax3v/3tEASCHauFuuuY09QRKGF1uyCS6QdqHRTqT4lDIHS8p3+kw7TnbWgCUsHq3Q5YUtANKzlfnZBB7cRoHecH6YMuJ0IA7XWUkhS6MsA5gU2oyuRMJ8CEiqgzU8qi4OOeNkJVFAmqgchgRU5uXUd23E0cp0/GqHbBSgI894/XHDnw04pVknwQfQpVrvNewhcmU3jcD0MaAiMmlclVjkkMiILUn+oEgnMxyO0wr9ShusMQq8nFFMENK1xNXihNvg6zmSfyjMuPQfK0GMqu5Tt8p4pGgR+8CBrpIBVzbzXPTgqN/Nn4Z+IDHbvBcRXIKzpSTEl0l14GgboPfPYSt2CP3x9d9NtBlVGIWWXCk5hB2dWlQpDvbfYKIpmpn9HVG8PG1SAxmEXHJjJe6e6KH6WQBGml6silTUeLsWpPEOkPdh48U2eHrc="
  distributions: "sdist"
  on:
    tags: true
    all_branches: true
    python: 3.5
